# Generated by Django 3.1.1 on 2020-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_short_name', models.CharField(max_length=100)),
                ('deadline', models.DateTimeField(verbose_name='deadline')),
                ('questions', models.ManyToManyField(to='surveys.Question')),
            ],
        ),
    ]
