# Generated by Django 3.1 on 2020-10-21 18:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201021_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
