# Generated by Django 3.1.1 on 2020-10-23 20:51

from django.db import migrations, models
import surveys.models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20201021_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.BigIntegerField(default=surveys.models.six_digits_id, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.BigIntegerField(default=surveys.models.ten_digits_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
