# Generated by Django 3.1 on 2020-10-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20201023_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('BS', 'Bachelor'), ('MS', 'Master')], default='BS', max_length=2)),
                ('year', models.CharField(default='19', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(null=True,default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='surveys.track'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='surveys.track'),
            preserve_default=False,
        ),
    ]
