# Generated by Django 3.1 on 2020-10-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20201024_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='surveys.track'),
        ),
    ]
