# Generated by Django 3.1 on 2020-10-24 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20201024_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='surveys.track'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='n.surname@innopolis.university', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='surveys.track'),
            preserve_default=False,
        ),
    ]
